[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_OCTOKIT_TOKEN"